#pragma once

#include <SDL3/SDL.h>

namespace ejff::gpu
{

enum class VertexElementFormat
{
    eInvalid = SDL_GPU_VERTEXELEMENTFORMAT_INVALID,

    eInt = SDL_GPU_VERTEXELEMENTFORMAT_INT,
    eInt2 = SDL_GPU_VERTEXELEMENTFORMAT_INT2,
    eInt3 = SDL_GPU_VERTEXELEMENTFORMAT_INT3,
    eInt4 = SDL_GPU_VERTEXELEMENTFORMAT_INT4,

    eUInt = SDL_GPU_VERTEXELEMENTFORMAT_UINT,
    eUInt2 = SDL_GPU_VERTEXELEMENTFORMAT_UINT2,
    eUInt3 = SDL_GPU_VERTEXELEMENTFORMAT_UINT3,
    eUInt4 = SDL_GPU_VERTEXELEMENTFORMAT_UINT4,

    eFloat = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT,
    eFloat2 = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2,
    eFloat3 = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3,
    eFloat4 = SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4,

    eByte2 = SDL_GPU_VERTEXELEMENTFORMAT_BYTE2,
    eByte4 = SDL_GPU_VERTEXELEMENTFORMAT_BYTE4,

    eUByte2 = SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2,
    eUByte4 = SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4,

    eByte2Norm = SDL_GPU_VERTEXELEMENTFORMAT_BYTE2_NORM,
    eByte4Norm = SDL_GPU_VERTEXELEMENTFORMAT_BYTE4_NORM,

    eUByte2Norm = SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2_NORM,
    eUByte4Norm = SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM,

    eShort2 = SDL_GPU_VERTEXELEMENTFORMAT_SHORT2,
    eShort4 = SDL_GPU_VERTEXELEMENTFORMAT_SHORT4,

    eUShort2 = SDL_GPU_VERTEXELEMENTFORMAT_USHORT2,
    eUShort4 = SDL_GPU_VERTEXELEMENTFORMAT_USHORT4,

    eShort2Norm = SDL_GPU_VERTEXELEMENTFORMAT_SHORT2_NORM,
    eShort4Norm = SDL_GPU_VERTEXELEMENTFORMAT_SHORT4_NORM,

    eUShort2Norm = SDL_GPU_VERTEXELEMENTFORMAT_USHORT2_NORM,
    eUShort4Norm = SDL_GPU_VERTEXELEMENTFORMAT_USHORT4_NORM,

    eHalf2 = SDL_GPU_VERTEXELEMENTFORMAT_HALF2,
    eHalf4 = SDL_GPU_VERTEXELEMENTFORMAT_HALF4
};

} // namespace ejff::gpu
